openapi: 3.2.0
info:
  title: Partner Health API
  version: '1.2'
tags:
- name: health
paths:
  /:
    get:
      tags:
      - health
      operationId: GetHealth
      responses:
        '200':
          description: OK
      security:
      - bearer: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2CodeEMIS-X-GP-PAPI:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            papi-appt.read: Read Appointments
            papi-appt.write: Write Appointments
            papi-cr.read: Read Clinical Record
            papi-cr.write: Write Clinical Record
            papi-subjects.read: Read Subjects
            papi-config.read: Read Config
            papi-searches.read: Read Searches
