openapi: 3.2.0
info:
  title: Partner Search API
  version: '1.2'
tags:
- name: search
paths:
  /api/v1/search/GetPatientSearches:
    get:
      tags:
      - search
      description: 'This call accepts the ID of a QOF (Quality Outcomes Framework) report and a report type. It returns a list of patients from the most recently run result set for that search.


        HAID (How Am I Driving) runs on the following intervals:

        1. How Am I Driving – Weekly (Wednesday and Weekend)

        2. End of Financial Year – Weekends only

        3. Look Ahead 1 and 3 Months – Runs based on available bandwidth


        Report Types:

        0 = 3 Month Look-Ahead

        1 = How Am I Driving

        2 = Financial Year End

        3 = 1 Month Look-Ahead'
      operationId: GetPatientSearches
      parameters:
      - name: searchGuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: site
        in: query
        required: true
        schema:
          type: string
      - name: reportType
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/PartnerApi.Service.Contracts.Search.ReportType'
      - name: applicationId
        in: header
        description: The applicationId (aka party key) will be provided by your assurance lead
        required: true
        schema:
          type: string
      responses:
        '500':
          description: Internal error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
        '400':
          description: Bad request - adjust URL or parameters
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
        '401':
          description: Authentication token not valid
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
        '404':
          description: Not found
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
        '415':
          description: Media type not valid for URL
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.Service.Model.ErrorResponse'
        '200':
          description: Retrieves search details
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PartnerApi.EmisOpen.PatientSearchesMatches.PatientMatches'
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerApi.EmisOpen.PatientSearchesMatches.PatientMatches'
      security:
      - bearer: []
      - OAuth2CodeEMIS-X-GP-PAPI:
        - papi-searches.read
components:
  schemas:
    PartnerApi.Service.Model.Details:
      type: object
      properties:
        text:
          type:
          - string
          - 'null'
        coding:
          $ref: '#/components/schemas/PartnerApi.Service.Model.Coding'
      additionalProperties: false
    PartnerApi.Service.Model.Issue:
      type: object
      properties:
        severity:
          $ref: '#/components/schemas/PartnerApi.Service.Model.SeverityType'
        code:
          type:
          - string
          - 'null'
        details:
          $ref: '#/components/schemas/PartnerApi.Service.Model.Details'
        diagnostics:
          type:
          - string
          - 'null'
      additionalProperties: false
    PartnerApi.Service.Model.Coding:
      type: object
      properties:
        system:
          type:
          - string
          - 'null'
        code:
          type:
          - string
          - 'null'
        display:
          type:
          - string
          - 'null'
      additionalProperties: false
    PartnerApi.EmisOpen.PatientSearchesMatches.PatientMatches:
      type: object
      properties:
        patientList:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PartnerApi.EmisOpen.PatientSearchesMatches.PatientType'
      additionalProperties: false
    PartnerApi.Service.Model.SeverityType:
      enum:
      - 0
      - 1
      type: integer
      format: int32
    PartnerApi.Service.Contracts.Search.ReportType:
      enum:
      - 0
      - 1
      - 2
      - 3
      type: integer
      format: int32
    PartnerApi.EmisOpen.PatientSearchesMatches.PatientType:
      type: object
      properties:
        refID:
          type: integer
          format: int32
        currentStatus:
          type: integer
          format: int32
      additionalProperties: false
    PartnerApi.Service.Model.ErrorResponse:
      type: object
      properties:
        messageId:
          type: string
          format: uuid
        text:
          $ref: '#/components/schemas/PartnerApi.Service.Model.Text'
        issue:
          $ref: '#/components/schemas/PartnerApi.Service.Model.Issue'
        legacyOutcome:
          type: integer
          format: int32
      additionalProperties: false
    PartnerApi.Service.Model.Text:
      type: object
      properties:
        status:
          type:
          - string
          - 'null'
        div:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2CodeEMIS-X-GP-PAPI:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            papi-appt.read: Read Appointments
            papi-appt.write: Write Appointments
            papi-cr.read: Read Clinical Record
            papi-cr.write: Write Clinical Record
            papi-subjects.read: Read Subjects
            papi-config.read: Read Config
            papi-searches.read: Read Searches
